import { lazy, Suspense, useState } from "react";
import ProjectDashboard from "./ProjectDashboard";

const HackathonStudio = lazy(() => import("./HackathonStudio"));
const InnovationReport = lazy(() => import("./InnovationReport"));
const ModelComparison = lazy(() => import("./ModelComparison"));
const ResearchEvidence = lazy(() => import("./ResearchEvidence"));

const list = (value) => Array.isArray(value) ? value : [];

export default function DesktopWorkspace({
  idea, result, provider, demoMode, loading, compareResults, savedProjects,
  research, researchLoading, researchError, showResearchPanel,
  onAnalyze, onEdit, onSave, onLoadResearch, onOpenProject, onDeleteProject, onUpdateProject,
}) {
  const [pdfLoading, setPdfLoading] = useState(false);
  const [pdfError, setPdfError] = useState("");
  const [submissionOpen, setSubmissionOpen] = useState(false);
  const riskColor = result?.patent_risk?.toLowerCase() === "low" ? "text-emerald-400" : result?.patent_risk?.toLowerCase() === "medium" ? "text-amber-400" : "text-rose-400";

  const downloadReport = async () => {
    if (!result) return;
    setPdfLoading(true);
    setPdfError("");
    try {
      const { default: jsPDF } = await import("jspdf");
      const pdf = new jsPDF({ unit: "mm", format: "a4" });
      const margin = 18;
      const contentWidth = 174;
      const pageBottom = 278;
      let y = 18;

      const ensureSpace = (height) => {
        if (y + height <= pageBottom) return;
        pdf.addPage();
        y = 18;
      };
      const write = (value, { size = 10, weight = "normal", color = [40, 48, 60], gap = 2 } = {}) => {
        if (!value) return;
        pdf.setFont("helvetica", weight);
        pdf.setFontSize(size);
        pdf.setTextColor(...color);
        const lines = pdf.splitTextToSize(String(value), contentWidth);
        const height = lines.length * size * 0.42 + gap;
        ensureSpace(height);
        pdf.text(lines, margin, y);
        y += height;
      };
      const section = (title, body) => {
        ensureSpace(16);
        y += 3;
        write(title.toUpperCase(), { size: 8, weight: "bold", color: [35, 139, 105], gap: 2 });
        write(body, { size: 10, gap: 3 });
      };
      const bullets = (items) => list(items).forEach((item) => write(`• ${item}`, { size: 9, gap: 1.5 }));

      write("INVENTAI DECISION BRIEF", { size: 8, weight: "bold", color: [35, 139, 105], gap: 4 });
      write(result.title, { size: 21, weight: "bold", color: [15, 23, 36], gap: 4 });
      write(result.one_liner, { size: 11, color: [70, 80, 94], gap: 5 });
      write(`${result.verdict || "VALIDATE"}  |  Innovation ${result.innovation_score}/100  |  Novelty ${result.novelty_score}/100  |  Feasibility ${result.feasibility_score}/100  |  Market ${result.market_score}/100`, { size: 8, weight: "bold", color: [15, 23, 36], gap: 5 });
      section("Submitted idea", idea);
      section("Biggest concern", list(result.risks)[0]);
      section("Critical experiment", result.next_experiment || result.prototype);
      section("Problem and users", `${result.problem}\n\nUsers: ${result.users}`);
      section("Defensible edge", result.differentiator || result.technology);
      section("Recommended actions", "");
      bullets(result.recommended_actions);
      section("Validation questions", "");
      bullets(result.validation_questions);
      section("Success thresholds", "");
      bullets(result.success_metrics);
      section("Three-phase plan", "");
      list(result.roadmap).forEach((step, index) => write(`${index + 1}. ${step.phase} (${step.duration}) — ${step.outcome}`, { size: 9, gap: 2 }));
      ensureSpace(18);
      y += 5;
      write("AI-generated decision support, not legal, patent, medical, or investment advice. Validate every important claim with qualified sources and real users.", { size: 7, color: [100, 110, 125] });
      pdf.save(`${(result.title || "InventAI-report").replace(/[^a-z0-9]+/gi, "-")}.pdf`);
    } catch {
      setPdfError("The PDF could not be created on this device. Try again from a desktop browser.");
    } finally {
      setPdfLoading(false);
    }
  };

  return <>
    {result && <section id="report" className="desktop-report"><div className="desktop-report__inner">
      {compareResults && <Suspense fallback={null}><ModelComparison results={compareResults} /></Suspense>}
      <div className="report-toolbar">
        <div><p className="section-kicker">Decision workspace</p><p>Generated by {result.provider || (demoMode ? "Example" : provider)}</p></div>
        <div className="report-actions">
          {demoMode && <span className="demo-label">Example data</span>}
          <details className="report-refine-menu">
            <summary>Refine analysis</summary>
            <div>
              <button type="button" onClick={() => onAnalyze("novelty")} disabled={loading || demoMode}>Improve originality</button>
              <button type="button" onClick={() => onAnalyze("breakthrough")} disabled={loading || demoMode}>Resolve a trade-off</button>
              <button type="button" onClick={() => onAnalyze("improve")} disabled={loading || demoMode}>Improve feasibility</button>
            </div>
          </details>
          <button type="button" onClick={onEdit}>Edit brief</button>
          <button type="button" onClick={onSave}>Save version</button>
          <button type="button" className="primary" onClick={downloadReport} disabled={pdfLoading}>{pdfLoading ? "Exporting..." : "Export brief"}</button>
        </div>
      </div>
      {pdfError && <p className="report-export-error" role="alert">{pdfError}</p>}
      {["novelty", "breakthrough"].includes(result.analysis_mode) && result.improved_idea && <aside className="improved-idea"><strong>{result.analysis_mode === "breakthrough" ? "Trade-off resolved" : "Reframed concept"}</strong><p>{result.improved_idea}</p></aside>}
      <Suspense fallback={<div className="workspace-loading">Opening decision brief...</div>}>
        <InnovationReport key={`${idea}-${result.title}`} idea={idea} result={result} patentRiskColor={riskColor} research={research} />
      </Suspense>
      <details className="submission-toolbox" onToggle={(event) => setSubmissionOpen(event.currentTarget.open)}>
        <summary><span><small>Optional workspace</small><strong>Hackathon submission tools</strong></span><b>Open</b></summary>
        {submissionOpen && <Suspense fallback={<div className="workspace-loading">Opening submission tools...</div>}>
          <HackathonStudio key={`${idea}-${result.title}-studio`} idea={idea} result={result} projects={savedProjects} />
        </Suspense>}
      </details>
    </div></section>}

    {showResearchPanel && <section id="research-evidence" className="desktop-evidence"><div><Suspense fallback={<div className="workspace-loading">Opening evidence...</div>}><ResearchEvidence evidence={research} loading={researchLoading} error={researchError} onRetry={onLoadResearch} /></Suspense></div></section>}
    {savedProjects.length > 0 && <ProjectDashboard projects={savedProjects} onOpen={onOpenProject} onDelete={onDeleteProject} onUpdate={onUpdateProject} />}
  </>;
}
