import { useState } from "react";
import InnovationRadar from "./InnovationRadar";
import SystemArchitecture from "./SystemArchitecture";
import JudgeReadiness from "./JudgeReadiness";
import ExperimentTracker from "./ExperimentTracker";
import { CapabilityMatrix, EvidenceScoreGrid } from "./EvidenceDecisionLayer";
import { useResearchEvidence } from "../services/researchStore";

const Icon = ({ children }) => <span className="grid h-9 w-9 shrink-0 place-items-center rounded-lg bg-cyan-400/10 text-sm font-bold text-cyan-300">{children}</span>;
const Detail = ({ icon, title, children }) => <div className="rounded-2xl border border-white/8 bg-white/[.025] p-5"><div className="mb-4 flex items-center gap-3"><Icon>{icon}</Icon><h3 className="font-bold text-white">{title}</h3></div><div className="text-sm leading-6 text-slate-400">{children}</div></div>;
const list = (value) => Array.isArray(value) ? value : [];

function InnovationReport({ idea, result, patentRiskColor }) {
  const research = useResearchEvidence();
  const [adjustedConfidence, setAdjustedConfidence] = useState(result.confidence_score ?? 50);
  const scores = [
    ["Innovation", result.innovation_score, "from-cyan-300 to-cyan-500", "innovation"],
    ["Novelty", result.novelty_score, "from-violet-300 to-violet-500", "novelty"],
    ["Feasibility", result.feasibility_score, "from-blue-300 to-blue-500", "feasibility"],
    ["Market", result.market_score ?? result.innovation_score, "from-emerald-300 to-emerald-500", "market"],
  ];
  return <article className="overflow-hidden rounded-3xl border border-white/10 bg-[#07111f] shadow-2xl">
    <header className="border-b border-white/8 bg-gradient-to-br from-cyan-400/10 via-transparent to-blue-500/10 p-6 md:p-10">
      <div className="flex flex-col gap-6 md:flex-row md:items-start md:justify-between"><div className="max-w-3xl"><p className="text-xs font-bold uppercase tracking-[.22em] text-cyan-400">InventAI decision brief</p><h1 className="mt-3 text-3xl font-black tracking-tight text-white md:text-5xl">{result.title}</h1><p className="mt-4 text-lg leading-7 text-slate-300">{result.one_liner || result.market_potential}</p></div><div className="flex shrink-0 flex-col items-start md:items-end"><span className="rounded-full border border-emerald-400/25 bg-emerald-400/10 px-4 py-2 text-sm font-black tracking-wider text-emerald-300">{result.verdict || "VALIDATE"}</span><span className={`mt-3 text-xs font-semibold ${patentRiskColor}`}>{result.patent_risk} patent risk*</span></div></div>
      <div className="mt-8 rounded-xl border border-white/8 bg-black/10 p-4 text-sm italic leading-6 text-slate-500">“{idea}”</div>
    </header>

    <div className="p-6 md:p-10">
      <section className="grid gap-4 md:grid-cols-3"><div className="rounded-2xl border border-emerald-400/15 bg-emerald-400/[.04] p-5"><p className="text-xs font-black uppercase tracking-wider text-emerald-300">The short answer</p><p className="mt-2 text-xl font-black text-white">{result.verdict === "PROMISING" ? "Worth testing" : result.verdict === "PIVOT" ? "Change direction first" : "Validate before building"}</p><p className="mt-2 text-xs leading-5 text-slate-500">This is a recommendation, not a guarantee.</p></div><div className="rounded-2xl border border-amber-400/15 bg-amber-400/[.04] p-5"><p className="text-xs font-black uppercase tracking-wider text-amber-300">Biggest concern</p><p className="mt-2 text-sm font-semibold leading-6 text-slate-200">{list(result.risks)[0] || "More real-world evidence is needed."}</p></div><div className="rounded-2xl border border-cyan-400/15 bg-cyan-400/[.04] p-5"><p className="text-xs font-black uppercase tracking-wider text-cyan-300">Do this next</p><p className="mt-2 text-sm font-semibold leading-6 text-slate-200">{result.next_experiment || result.prototype}</p></div></section>

      <section className="mt-12"><div className="mb-5 flex items-end justify-between"><div><p className="section-kicker">Decision dashboard</p><h2 className="section-title">Is this idea worth building?</h2></div><span className="hidden text-xs text-slate-600 sm:block">AI estimates · validate with evidence</span></div><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{scores.map(([name, score, color, key]) => <div key={name} className="score-card"><div className="flex items-end justify-between"><span className="text-sm text-slate-400">{name}</span><strong className="text-3xl text-white">{score}</strong></div><div className="mt-4 h-1.5 overflow-hidden rounded-full bg-slate-800"><div className={`h-full rounded-full bg-gradient-to-r ${color}`} style={{ width: `${score}%` }} /></div><p className="mt-3 text-xs leading-5 text-slate-500">{result.score_explanations?.[key] || "Directional estimate based on the submitted idea."}</p></div>)}</div></section>

      <section className="mt-12 grid gap-6 lg:grid-cols-[1.1fr_.9fr]"><div><p className="section-kicker">Strategic diagnosis</p><h2 className="section-title">Why it can win</h2><div className="mt-5 grid gap-4 sm:grid-cols-2"><Detail icon="01" title="Problem">{result.problem}</Detail><Detail icon="02" title="Defensible edge">{result.differentiator || result.technology}</Detail><Detail icon="03" title="Target users">{result.users}</Detail><Detail icon="04" title="Business model">{result.business_model || result.market_potential}</Detail></div></div><InnovationRadar innovationScore={result.innovation_score} noveltyScore={result.novelty_score} feasibilityScore={result.feasibility_score} marketScore={result.market_score} /></section>

      {(list(result.strengths).length > 0 || list(result.risks).length > 0) && <section className="mt-12 grid gap-5 md:grid-cols-2"><div className="rounded-2xl border border-emerald-400/15 bg-emerald-400/[.04] p-6"><p className="section-kicker text-emerald-400">Signals</p><h2 className="mb-5 text-xl font-bold">What works</h2>{list(result.strengths).map((x) => <div key={x} className="mb-3 flex gap-3 text-sm text-slate-300"><span className="text-emerald-400">✓</span>{x}</div>)}</div><div className="rounded-2xl border border-amber-400/15 bg-amber-400/[.04] p-6"><p className="section-kicker text-amber-400">Watchlist</p><h2 className="mb-5 text-xl font-bold">What could break</h2>{list(result.risks).map((x) => <div key={x} className="mb-3 flex gap-3 text-sm text-slate-300"><span className="text-amber-400">!</span>{x}</div>)}</div></section>}

      {(list(result.critical_assumptions).length > 0 || list(result.validation_questions).length > 0) && <section className="mt-12 rounded-2xl border border-fuchsia-400/15 bg-gradient-to-br from-fuchsia-400/[.06] to-cyan-400/[.03] p-6 md:p-8"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="section-kicker text-fuchsia-300">Validation command center</p><h2 className="section-title">Turn assumptions into proof</h2></div><div className="text-right"><div className="text-3xl font-black text-white">{result.confidence_score ?? 50}%</div><div className="text-[11px] uppercase tracking-wider text-slate-500">analysis confidence</div></div></div><div className="mt-6 grid gap-5 lg:grid-cols-3"><div><h3 className="mb-3 text-sm font-bold text-amber-300">Critical assumptions</h3>{list(result.critical_assumptions).map((x, i) => <div key={x} className="mb-3 rounded-xl border border-white/8 bg-black/10 p-3 text-sm leading-5 text-slate-300"><span className="mr-2 font-black text-amber-400">A{i + 1}</span>{x}</div>)}</div><div><h3 className="mb-3 text-sm font-bold text-cyan-300">Ask customers</h3>{list(result.validation_questions).map((x, i) => <div key={x} className="mb-3 rounded-xl border border-white/8 bg-black/10 p-3 text-sm leading-5 text-slate-300"><span className="mr-2 font-black text-cyan-400">Q{i + 1}</span>{x}</div>)}</div><div><h3 className="mb-3 text-sm font-bold text-emerald-300">Proof thresholds</h3>{list(result.success_metrics).map((x, i) => <div key={x} className="mb-3 rounded-xl border border-white/8 bg-black/10 p-3 text-sm leading-5 text-slate-300"><span className="mr-2 font-black text-emerald-400">M{i + 1}</span>{x}</div>)}</div></div></section>}

      <JudgeReadiness readiness={result.judge_readiness} />

      {list(result.competitors).length > 0 && <section className="mt-12"><p className="section-kicker">Competitive landscape</p><h2 className="section-title">Alternatives and open gaps</h2><div className="mt-6 grid gap-4 md:grid-cols-3">{result.competitors.map((item)=><div key={item.name} className="rounded-2xl border border-white/8 bg-white/[.025] p-5"><h3 className="font-bold text-white">{item.name}</h3><p className="mt-2 text-xs leading-5 text-slate-500">{item.approach}</p><div className="mt-4 border-t border-white/6 pt-3 text-xs leading-5 text-cyan-300"><strong>Gap:</strong> {item.gap}</div></div>)}</div><div className="mt-4 flex flex-wrap gap-2">{list(result.market_gaps).map((gap)=><span key={gap} className="rounded-full border border-cyan-400/15 bg-cyan-400/5 px-3 py-1.5 text-xs text-cyan-200">{gap}</span>)}</div><p className="mt-3 text-[11px] text-slate-600">Likely alternatives generated by AI; not live market research.</p></section>}

      <section className="mt-12"><p className="section-kicker">Execution roadmap</p><h2 className="section-title">From concept to evidence</h2><div className="mt-6 grid gap-4 md:grid-cols-3">{(result.roadmap || []).map((step, i) => <div key={step.phase} className="relative rounded-2xl border border-white/8 bg-white/[.025] p-5"><span className="text-xs font-black text-cyan-400">0{i + 1} · {step.duration}</span><h3 className="mt-3 text-lg font-bold">{step.phase}</h3><p className="mt-2 text-sm leading-6 text-slate-400">{step.outcome}</p>{step.estimated_cost && <p className="mt-3 text-xs font-semibold text-emerald-300">{step.estimated_cost}</p>}{step.skills?.length>0 && <p className="mt-2 text-xs text-slate-600">Skills: {step.skills.join(", ")}</p>}</div>)}</div></section>

      {list(result.recommended_actions).length > 0 && <section className="mt-12 grid gap-5 md:grid-cols-2"><div className="rounded-2xl border border-blue-400/15 bg-blue-400/[.035] p-6"><p className="section-kicker">Recommended actions</p><h2 className="mb-5 text-xl font-bold">What to do next</h2>{result.recommended_actions.map((x,i)=><div key={x} className="mb-3 flex gap-3 text-sm text-slate-300"><span className="font-black text-cyan-400">{i+1}.</span>{x}</div>)}</div><div className="rounded-2xl border border-violet-400/15 bg-violet-400/[.035] p-6"><p className="section-kicker text-violet-300">Idea upgrades</p><h2 className="mb-5 text-xl font-bold">How to improve it</h2>{list(result.improvement_suggestions).map((x)=><div key={x} className="mb-3 flex gap-3 text-sm text-slate-300"><span className="text-violet-300">↗</span>{x}</div>)}</div></section>}

      <section className="mt-12"><SystemArchitecture blocks={result.architecture_blocks || []} hardware={result.required_hardware || []} /></section>

      <section className="mt-12 rounded-2xl border border-cyan-400/20 bg-gradient-to-r from-cyan-400/10 to-blue-500/10 p-6 md:p-8"><div className="flex flex-col gap-4 md:flex-row md:items-center md:justify-between"><div><p className="section-kicker">Highest-value next move</p><h2 className="mt-1 text-xl font-bold text-white md:text-2xl">{result.next_experiment || result.prototype}</h2></div><span className="shrink-0 rounded-xl bg-cyan-300 px-4 py-2 text-xs font-black uppercase tracking-wider text-slate-950">Run this first</span></div></section>
      <section className="mt-8 grid gap-4 md:grid-cols-3"><Detail icon="$" title="Pilot budget">{result.estimated_cost}</Detail><Detail icon="T" title="Suggested stack">{result.technology}</Detail><Detail icon="↗" title="Market potential">{result.market_potential}</Detail></section>
      <footer className="mt-10 border-t border-white/8 pt-5 text-xs leading-5 text-slate-600"><strong className="text-amber-400">Patent status: AI estimate only.</strong> No live patent database was searched. This is not a legal opinion. Validate claims, competitors, market assumptions, and technical feasibility with qualified sources.</footer>
      <EvidenceScoreGrid result={result} research={research} adjustedConfidence={adjustedConfidence} />
      <CapabilityMatrix idea={idea} result={result} research={research} />
      <ExperimentTracker idea={idea} result={result} onConfidenceChange={setAdjustedConfidence} />
    </div>
  </article>;
}
export default InnovationReport;
