import { useMemo, useState } from "react";
import SavedProjectCard from "./SavedProjectCard";

function ProjectDashboard({ projects, onOpen, onDelete, onUpdate }) {
  const [query, setQuery] = useState(""); const [sort, setSort] = useState("newest"); const [favoritesOnly, setFavoritesOnly] = useState(false);
  const visible = useMemo(() => projects.filter((p) => (!favoritesOnly || p.favorite) && `${p.name || ""} ${p.result?.title || ""} ${p.idea}`.toLowerCase().includes(query.toLowerCase())).sort((a,b) => sort === "score" ? (b.result?.innovation_score || 0) - (a.result?.innovation_score || 0) : sort === "name" ? (a.name || a.result?.title || "").localeCompare(b.name || b.result?.title || "") : b.id-a.id), [projects, query, sort, favoritesOnly]);
  return <section className="border-t border-white/5 px-5 py-16"><div className="mx-auto max-w-6xl"><div className="flex flex-col gap-4 md:flex-row md:items-end md:justify-between"><div><p className="section-kicker">Project dashboard</p><h2 className="section-title">Saved inventions</h2></div><div className="flex flex-wrap gap-2"><input aria-label="Search saved inventions" value={query} onChange={(e)=>setQuery(e.target.value)} placeholder="Search projects…" className="rounded-xl border border-white/10 bg-slate-900 px-4 py-2 text-sm outline-none focus:border-cyan-400/50"/><select aria-label="Sort projects" value={sort} onChange={(e)=>setSort(e.target.value)} className="rounded-xl border border-white/10 bg-slate-900 px-3 py-2 text-sm"><option value="newest">Newest</option><option value="score">Highest score</option><option value="name">Name</option></select><button onClick={()=>setFavoritesOnly(!favoritesOnly)} className={`rounded-xl border px-3 py-2 text-sm ${favoritesOnly ? "border-amber-400/40 bg-amber-400/10 text-amber-300" : "border-white/10"}`}>★ Favorites</button></div></div><div className="mt-6 grid gap-4 md:grid-cols-2">{visible.map((p)=><SavedProjectCard key={p.id} project={p} onOpen={onOpen} onDelete={onDelete} onRename={(name)=>onUpdate(p.id,{name})} onFavorite={()=>onUpdate(p.id,{favorite:!p.favorite})}/>)}</div>{visible.length===0 && <div className="mt-6 rounded-2xl border border-dashed border-white/10 p-10 text-center text-sm text-slate-500">No projects match these filters.</div>}</div></section>;
}
export default ProjectDashboard;
